// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EffectParticleElementInitColor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EffectParticleElementInitColor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

colorMinValue():number {
  return this.bb!.readUint32(this.bb_pos);
}

colorMaxValue():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createEffectParticleElementInitColor(builder:flatbuffers.Builder, ColorMinValue: number, ColorMaxValue: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(ColorMaxValue);
  builder.writeInt32(ColorMinValue);
  return builder.offset();
}

}
