// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EffectParticleElementAlphaFade {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):EffectParticleElementAlphaFade {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

disprangeMinValue():number {
  return this.bb!.readFloat32(this.bb_pos);
}

disprangeMaxValue():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createEffectParticleElementAlphaFade(builder:flatbuffers.Builder, disprangeMinValue: number, disprangeMaxValue: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(disprangeMaxValue);
  builder.writeFloat32(disprangeMinValue);
  return builder.offset();
}

}
