// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EffectParticleElementGravity {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EffectParticleElementGravity {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

gravityX():number {
  return this.bb!.readFloat32(this.bb_pos);
}

gravityY():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createEffectParticleElementGravity(builder:flatbuffers.Builder, Gravity_x: number, Gravity_y: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(Gravity_y);
  builder.writeFloat32(Gravity_x);
  return builder.offset();
}

}
