// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EffectParticleElementRotationTrans {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):EffectParticleElementRotationTrans {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

RotationFactor():number {
  return this.bb!.readFloat32(this.bb_pos);
}

EndLifeTimePer():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createEffectParticleElementRotationTrans(builder:flatbuffers.Builder, RotationFactor: number, EndLifeTimePer: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(EndLifeTimePer);
  builder.writeFloat32(RotationFactor);
  return builder.offset();
}

}
