// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EffectParticlePointGravity {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):EffectParticlePointGravity {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

PositionX():number {
  return this.bb!.readFloat32(this.bb_pos);
}

PositionY():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

Power():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

static sizeOf():number {
  return 12;
}

static createEffectParticlePointGravity(builder:flatbuffers.Builder, Position_x: number, Position_y: number, Power: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.writeFloat32(Power);
  builder.writeFloat32(Position_y);
  builder.writeFloat32(Position_x);
  return builder.offset();
}

}
