// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EffectParticleElementTransSpeed {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EffectParticleElementTransSpeed {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

speedMinValue():number {
  return this.bb!.readFloat32(this.bb_pos);
}

speedMaxValue():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createEffectParticleElementTransSpeed(builder:flatbuffers.Builder, SpeedMinValue: number, SpeedMaxValue: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(SpeedMaxValue);
  builder.writeFloat32(SpeedMinValue);
  return builder.offset();
}

}
