// automatically generated by the FlatBuffers compiler, do not modify

export enum SsPartType{
  Invalid = -1,
  Nulltype = 0,
  Normal = 1,
  Text = 2,
  Instance = 3,
  Armature = 4,
  Effect = 5,
  Mesh = 6,
  Movenode = 7,
  Constraint = 8,
  Mask = 9,
  Joint = 10,
  Bonepoint = 11
}

