// automatically generated by the FlatBuffers compiler, do not modify

import { userDataInteger } from '../../ss/ssfb/user-data-integer.js';
import { userDataPoint } from '../../ss/ssfb/user-data-point.js';
import { userDataRect } from '../../ss/ssfb/user-data-rect.js';
import { userDataString } from '../../ss/ssfb/user-data-string.js';


export enum userDataValue {
  NONE = 0,
  userDataInteger = 1,
  userDataRect = 2,
  userDataPoint = 3,
  userDataString = 4
}

export function unionTouserDataValue(
  type: userDataValue,
  accessor: (obj:userDataInteger|userDataPoint|userDataRect|userDataString) => userDataInteger|userDataPoint|userDataRect|userDataString|null
): userDataInteger|userDataPoint|userDataRect|userDataString|null {
  switch(userDataValue[type]) {
    case 'NONE': return null; 
    case 'userDataInteger': return accessor(new userDataInteger())! as userDataInteger;
    case 'userDataRect': return accessor(new userDataRect())! as userDataRect;
    case 'userDataPoint': return accessor(new userDataPoint())! as userDataPoint;
    case 'userDataString': return accessor(new userDataString())! as userDataString;
    default: return null;
  }
}

export function unionListTouserDataValue(
  type: userDataValue, 
  accessor: (index: number, obj:userDataInteger|userDataPoint|userDataRect|userDataString) => userDataInteger|userDataPoint|userDataRect|userDataString|null, 
  index: number
): userDataInteger|userDataPoint|userDataRect|userDataString|null {
  switch(userDataValue[type]) {
    case 'NONE': return null; 
    case 'userDataInteger': return accessor(index, new userDataInteger())! as userDataInteger;
    case 'userDataRect': return accessor(index, new userDataRect())! as userDataRect;
    case 'userDataPoint': return accessor(index, new userDataPoint())! as userDataPoint;
    case 'userDataString': return accessor(index, new userDataString())! as userDataString;
    default: return null;
  }
}
