// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { userDataItem } from '../../ss/ssfb/user-data-item.js';


export class userDataPerFrame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):userDataPerFrame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsuserDataPerFrame(bb:flatbuffers.ByteBuffer, obj?:userDataPerFrame):userDataPerFrame {
  return (obj || new userDataPerFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsuserDataPerFrame(bb:flatbuffers.ByteBuffer, obj?:userDataPerFrame):userDataPerFrame {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new userDataPerFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

frameIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

data(index: number, obj?:userDataItem):userDataItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new userDataItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startuserDataPerFrame(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addFrameIndex(builder:flatbuffers.Builder, frameIndex:number) {
  builder.addFieldInt16(0, frameIndex, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static enduserDataPerFrame(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createuserDataPerFrame(builder:flatbuffers.Builder, frameIndex:number, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  userDataPerFrame.startuserDataPerFrame(builder);
  userDataPerFrame.addFrameIndex(builder, frameIndex);
  userDataPerFrame.addData(builder, dataOffset);
  return userDataPerFrame.enduserDataPerFrame(builder);
}
}
