// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class userDataRect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):userDataRect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readInt32(this.bb_pos);
}

y():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

w():number {
  return this.bb!.readInt32(this.bb_pos + 8);
}

h():number {
  return this.bb!.readInt32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createuserDataRect(builder:flatbuffers.Builder, x: number, y: number, w: number, h: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeInt32(h);
  builder.writeInt32(w);
  builder.writeInt32(y);
  builder.writeInt32(x);
  return builder.offset();
}

}
