// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class userDataInteger {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):userDataInteger {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

integer():number {
  return this.bb!.readInt32(this.bb_pos);
}

static sizeOf():number {
  return 4;
}

static createuserDataInteger(builder:flatbuffers.Builder, integer: number):flatbuffers.Offset {
  builder.prep(4, 4);
  builder.writeInt32(integer);
  return builder.offset();
}

}
