// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ss6player-rpgmakermz","status":true,"description":"SpriteStudio 6 アニメーション再生プラグイン","parameters":{"animationDir":"img/ssfb","replaceSVActorSpriteFlag":"true","svActorDir":"img/ssfb/sv_actors","svActorAnimationPack":"motions","svActorHideWeaponGraphics":"true","replaceSVEnemySpriteFlag":"true","svEnemyDir":"img/ssfb/sv_enemies","svEnemyAnimationPack":"motions","svEnemyAnimationName":"walk"}}
];
