// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ss6player-rpgmakermz","status":true,"description":"SpriteStudio 6 アニメーション再生プラグイン","parameters":{"animationDir":"img/ssfb"}}
];
