// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ss6player-rpgmakermz","status":true,"description":"RPG ツクール MZ で動作する SS6Player プラグインです。","parameters":{"animationDir":"img/ssfb"}},
{"name":"sample","status":true,"description":"sample","parameters":{}}
];
